---
- name: install mysql
  apt: name={{ item }} state=present
  with_items:
    - libmysqlclient-dev
    - mysql-server # 14.14
    - python-dev
    - python-pip

- name: install pip modules
  pip: name={{ item }}
  with_items:
    - mysql-python
    
- name: copy original config file
  command: cp /etc/mysql/my.cnf /etc/mysql/my.cnf.orig

- name: create user
  mysql_user:
    name=vagrant
    password=
    priv=*.*:ALL
    state=present

- name: create database
  mysql_db:
    name=vagrant
    state=present