---
- name: install dependent packages
  apt: name={{ item }} state=present
  with_items:
    - autoconf
    - bison
    - libffi-dev
    - libreadline6-dev
    - libssl-dev
    - zlib1g-dev

- name: exist check
  shell: test -e /usr/local/src/ruby
  register: exist_check
  ignore_errors: yes

- name: git clone
  git: repo=https://github.com/ruby/ruby.git
    dest=/usr/local/src/ruby
    version={{ ruby_git_version }}
  when: exist_check|failed

- name: compile & install
  shell:
    chdir=/usr/local/src/ruby
    autoconf
    && ./configure --disable-install-doc
    && make
    && make install

- name: uninstall old version
  apt: name={{ item }} state=absent
  with_items:
    - ruby
