---
- name: exit check
  shell: test -e /usr/local/src/zsh
  register: exit_check
  ignore_errors: yes

- name: git clone
  git: repo=https://github.com/zsh-users/zsh.git
  dest=/usr/local/src/zsh
  version=zsh-5.0.8
  when: exist_check|failed

- name: compile & install
  shell:
    chdir=/usr/local/src/zsh
    ./Util/preconfig
    && ./configure
    && make
    && make install.bin
    && make install.modules
    && make install.fns